config/routes.rb
Provider::Application.routes.draw do

   name_regex = /[A-Za-z0-9\.\-_]+?/

  scope "#{BASE_URL}" do

    match '/oauth_clients/list_pocs', to: 'oauth_clients#list_pocs', as: :list_pocs
    resources :oauth_clients
    
    match '/oauth/test_request',          :to => 'oauth#test_request',          :as => :test_request
    match '/oauth/token',                 :to => 'oauth#token',                 :as => :token
    match '/oauth/access_token',          :to => 'oauth#access_token',          :as => :access_token
    match '/oauth/request_token',         :to => 'oauth#request_token',         :as => :request_token
    match '/oauth/authorize',             :to => 'oauth#authorize',             :as => :authorize
    match '/oauth/authorize_cli',         :to => 'oauth#authorize_cli',         :as => :authorize_cli
    match '/oauth/authorize_switch_user', :to => 'oauth#authorize_switch_user', :as => :authorize_switch_user
    match '/oauth',                       :to => 'oauth#index',                 :as => :oauth
    match '/oauth/authenticate',          :to => 'oauth#authorize',             :as => :authorize
  
    #Jenkins routes
    match '/login/oauth/authorize',     :to => 'oauth#authorize',     :as => :authorize
    match '/login/oauth/access_token',  :to => 'oauth#access_token',  :as => :access_token
    match '/login/oauth/request_token', :to => 'oauth#request_token', :as => :request_token
    match '/login/oauth/token',         :to => 'oauth#token',         :as => :token    
    
    match '/oauth/login',        :to => 'oauth#login',        :as => :login
    match '/oauth/login_as',     :to => 'oauth#login_as',     :as => :login_as
    match '/oauth/be_admin',     :to => 'oauth#be_admin',     :as => :be_admin
    match '/oauth/be_developer', :to => 'oauth#be_developer', :as => :be_developer
    
  	#API Documentation
  	match '/rest_api', :to => 'rest_api#index'
  	
    match '/authenticate',          :to => 'application#authenticate'
    match '/authenticate_user',     :to => 'application#authenticate_user'
    match '/authentication_failed', :to => 'application#authentication_failed'
    
    root :to => "application#index"
 
    namespace :api do
      match "getInfo"                      => "user#info" #keep old naming used in first version
      match "user.info"                    => "user#info"
      match "user.all_info"                => "user#all_info"
      match "user.name"                    => "user#name"
      match "user.login"                   => "user#login"
      match "user.email"                   => "user#email"
      match "user.groups"                  => "user#groups"
      match "user.all_groups"              => "user#all_groups"
      match "user.firstname"               => "user#firstname"
      match "user.lastname"                => "user#lastname"
      match "user.belongs_to_group"        => "user#belongs_to_group"
      match "user.all_info"                => "user#all_info"      
      match "users/:name"                  => "users#user_info", :name => name_regex, :format => /json|xml|yaml/
      match "users/:name/belongs_to_group" => "users#user_belongs_to_group" , :name =>name_regex, :format => /json|xml|yaml/
      match "users/:name/get_devserver"    => "users#user_devserver", :name => name_regex, :format => /json|xml|yaml/
      match "users/:name/all_info"         => "users#user_all_info", :name => name_regex, :format => /json|xml|yaml/
      match "users/:name/groups"           => "users#user_groups", :name => name_regex, :format => /json|xml|yaml/
      match "users/:name/all_groups"       => "users#user_all_groups", :name => name_regex, :format => /json|xml|yaml/
    end
 
    match "/check" => "application#check"
    match "/401"   => "errors#unauthorized"
    match "/404"   => "errors#not_found"
    match '*path'  => "errors#not_found"
     
  end
  
end

app/controllers/oauth_controller.rb
require 'oauth/controllers/provider_controller'
class OauthController < ApplicationController

  add_breadcrumb "Authentication", {:controller => "oauth", :action => "login"}, {:use_icon => "icon-th"}


  # Action to change current user role to admin If applicable
  #
  # * *Call*    :
  #   - GET /BASE_URL/oauth/be_admin
  # * *Formats*    :
  #   - html
  #
  def be_admin
    if current_user.switch_to("admin")
      flash[:notice] = "You have now an 'admin' role"
    else
      flash[:error] = "You are not authorized to have a 'admin' role"
    end
    redirect_to( request.env["HTTP_REFERER"])
  end

  # Action to change current user role to developer If applicable
  #
  # * *Call*    :
  #   - GET /BASE_URL/oauth/be_developer
  # * *Formats*    :
  #   - html
  #
  def be_developer
    if current_user.switch_to("developer")
      flash[:notice] = "You have now a 'developer' role"
    else
      flash[:error] = "You are not authorized to have a 'developer' role"
    end
    redirect_to( request.env["HTTP_REFERER"] )
  end

  # Action to allow a user to get logged with other credentials
  #
  # * *Call*    :
  #   - GET /BASE_URL/oauth/login
  # * *Formats*    :
  #   - html
  #
  def login
    #If we go to login page we clear all data still in session to force a re-auth
    current_user = nil
    session[:user_id] = nil
    session["REMOTE_USER"] = nil
    env["REMOTE_USER"] = nil
     if params[:redirect_uri].nil? or params[:client_id].nil?
       redirect_to root_path
     else
      @from_application = ClientApplication.find_by_callback_url(params[:redirect_uri])
       if @from_application.nil?
         redirect_to root_path
       end
     end


  end

  include OAuth::Controllers::ProviderController

  alias :login_required :authenticate_user!

  # Action to manage authorization possibilities
  # 1 - Request comes from the login page, we will render the redirect_uri of the client application
  #
  # * *Call*    :
  #   - GET/POST /BASE_URL/oauth/authorize
  # * *Formats*    :
  #   - html
  #
      def authorize
        if params[:response_type].nil?
          params[:response_type] = "code"
        end
        @authorizer = OAuth::Provider::Authorizer.new current_user, true, params
        client_application = ClientApplication.find_by_key(params[:client_id])
        statsd = StatsManager.new
        statsd.feedAuthorizeMetric(current_user, client_application)
        #If this is an auto authentication transparent for end user
        redirect_to @authorizer.redirect_uri
      end

  # Action to manage authorization possibilities
  # 21- Request comes from a command line tool, we will render the token value
  #
  # * *Call*    :
  #   - GET/POST /BASE_URL/oauth/authorize_cli
  # * *Formats*    :
  #   - html
  #
      def authorize_cli
        authenticate_user!
        if params[:response_type].nil?
          params[:response_type] = "code"
        end
        @authorizer = OAuth::Provider::Authorizer.new current_user, true, params
        client_application = ClientApplication.find_by_key(params[:client_id])
        statsd = StatsManager.new
        statsd.feedAuthorizeMetric(current_user, client_application)
        render :text => @authorizer.code.token
      end


  # Action to manage authorization possibilities
  # 1 - Request comes from a client application, we will redirect user to redirect_uri
  #
  # * *Call*    :
  #   - GET/POST /BASE_URL/oauth/authorize_switch_user
  # * *Formats*    :
  #   - html
  #
      def authorize_switch_user
        authenticate_user!
        if params[:response_type].nil?
          params[:response_type] = "code"
        end
        @authorizer = OAuth::Provider::Authorizer.new current_user, true, params
        render :text => @authorizer.redirect_uri
      end
end

app/views/oauth/authorize.html.erb
<h1>Authorize access to your account</h1>
<p>Would you like to authorize <%= link_to @token.client_application.name,@token.client_application.url %> (<%= link_to @token.client_application.url,@token.client_application.url %>) to access your account?</p>
<%= form_tag authorize_url do %>
  <%= hidden_field_tag "oauth_token", @token.token %>
  <%- if params[:oauth_callback] -%>
  <%= hidden_field_tag "oauth_callback", params[:oauth_callback] %>
<%- end -%>
<p>
  <%= check_box_tag 'authorize' %> authorize access
</p>
<p>
  <%= submit_tag %>
</p>
<% end %>

app/views/oauth/authorize_failure.html.erb
<h1>You have disallowed this request</h1>

app/views/oauth/authorize_success.html.erb
<h1>You have allowed this request</h1>

app/views/oauth/login.html.erb
<h4><%=flash[:error]%></h4>

<div id='error_msg'></div>

<div class="form-signin">
    <small><b>The switch user feature is only compatible with Google Chrome web browser.</b></small><br/><br/>
    <h2 class="form-signin-heading">Please sign-in</h2>
     <input type="text" placeholder="Enter a Windows login" class="input-block-level" id="login">
     <input type="password" placeholder="Enter a Windows password" class="input-block-level" id="password">


    <%= hidden_field_tag :redirect_uri, params[:redirect_uri] %>
    <%= hidden_field_tag :client_id, params[:client_id] %>
    <%= hidden_field_tag :response_type, params[:response_type] %>
    <%= hidden_field_tag :state, params[:state] %>
    <%= hidden_field_tag :scope, params[:scope] %>

    <%= button_tag "Get connected!", :onclick => "submitForm()", :id => "btn_signin", :class=>"btn btn-large btn-primary" %>
    <i><span class="help-block" align="center">You will be automatically redirected to<br /><b><a href="<%=@from_application.url%>" target="_blank"><%=@from_application.name%></a></b></span></i>
</div>

<script>



/**
*
*  Base64 encode / decode
*  http://www.webtoolkit.info/
*
**/

var Base64 = {

  // private property
  _keyStr : "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",

  // public method for encoding
  encode : function (input) {
    var output = "";
    var chr1, chr2, chr3, enc1, enc2, enc3, enc4;
    var i = 0;

    input = Base64._utf8_encode(input);

    while (i < input.length) {

      chr1 = input.charCodeAt(i++);
      chr2 = input.charCodeAt(i++);
      chr3 = input.charCodeAt(i++);

      enc1 = chr1 >> 2;
      enc2 = ((chr1 & 3) << 4) | (chr2 >> 4);
      enc3 = ((chr2 & 15) << 2) | (chr3 >> 6);
      enc4 = chr3 & 63;

      if (isNaN(chr2)) {
        enc3 = enc4 = 64;
      } else if (isNaN(chr3)) {
        enc4 = 64;
      }

      output = output +
      this._keyStr.charAt(enc1) + this._keyStr.charAt(enc2) +
      this._keyStr.charAt(enc3) + this._keyStr.charAt(enc4);

    }

    return output;
  },

  // public method for decoding
  decode : function (input) {
    var output = "";
    var chr1, chr2, chr3;
    var enc1, enc2, enc3, enc4;
    var i = 0;

    input = input.replace(/[^A-Za-z0-9\+\/\=]/g, "");

    while (i < input.length) {

      enc1 = this._keyStr.indexOf(input.charAt(i++));
      enc2 = this._keyStr.indexOf(input.charAt(i++));
      enc3 = this._keyStr.indexOf(input.charAt(i++));
      enc4 = this._keyStr.indexOf(input.charAt(i++));

      chr1 = (enc1 << 2) | (enc2 >> 4);
      chr2 = ((enc2 & 15) << 4) | (enc3 >> 2);
      chr3 = ((enc3 & 3) << 6) | enc4;

      output = output + String.fromCharCode(chr1);

      if (enc3 != 64) {
        output = output + String.fromCharCode(chr2);
      }
      if (enc4 != 64) {
        output = output + String.fromCharCode(chr3);
      }

    }

    output = Base64._utf8_decode(output);

    return output;

  },

  // private method for UTF-8 encoding
  _utf8_encode : function (string) {
    string = string.replace(/\r\n/g,"\n");
    var utftext = "";

    for (var n = 0; n < string.length; n++) {

      var c = string.charCodeAt(n);

      if (c < 128) {
        utftext += String.fromCharCode(c);
      }
      else if((c > 127) && (c < 2048)) {
        utftext += String.fromCharCode((c >> 6) | 192);
        utftext += String.fromCharCode((c & 63) | 128);
      }
      else {
        utftext += String.fromCharCode((c >> 12) | 224);
        utftext += String.fromCharCode(((c >> 6) & 63) | 128);
        utftext += String.fromCharCode((c & 63) | 128);
      }

    }

    return utftext;
  },

  // private method for UTF-8 decoding
  _utf8_decode : function (utftext) {
    var string = "";
    var i = 0;
    var c = c1 = c2 = 0;

    while ( i < utftext.length ) {

      c = utftext.charCodeAt(i);

      if (c < 128) {
        string += String.fromCharCode(c);
        i++;
      }
      else if((c > 191) && (c < 224)) {
        c2 = utftext.charCodeAt(i+1);
        string += String.fromCharCode(((c & 31) << 6) | (c2 & 63));
        i += 2;
      }
      else {
        c2 = utftext.charCodeAt(i+1);
        c3 = utftext.charCodeAt(i+2);
        string += String.fromCharCode(((c & 15) << 12) | ((c2 & 63) << 6) | (c3 & 63));
        i += 3;
      }

    }

    return string;
  }

}

function make_basic_auth(user, password) {
  var tok = user + ':' + password;
  var hash = Base64.encode(tok);
  return "Basic " + hash;
}

function submitForm()
{
  $.blockUI(
    {
      name: "loading_block",
      message: '<h1>Redirecting to <br /><%=@from_application.name%></h1><br />Please wait...',
      css: {
              border: 'none',
              padding: '15px',
              backgroundColor: '#000',
              '-webkit-border-radius': '10px',
              '-moz-border-radius': '10px',
              opacity: .5,
              color: '#fff'
              }
    }
  );

  var auth = make_basic_auth($("input[id=login]").val(),$("input[id=password]").val());
  var url = "/<%= "#{BASE_URL}" %>/oauth/authorize_switch_user";
  var formData = "redirect_uri="+$("input[id=redirect_uri]").val()+"&"+"response_type="+$("input[id=response_type]").val()+"&"+"client_id="+$("input[id=client_id]").val()+"&"+"state="+$("input[id=state]").val();

  // jQuery
  $.ajax({
      url : url,
      type: 'POST',
      data : formData,
      beforeSend : function(req) {
           req.setRequestHeader('Authorization', auth);
      },
     complete: function(xhr,textStatus) {
     if (xhr.status == 200) {
       location.href = xhr.responseText;
     }else if(xhr.status == 500) {
       $.unblockUI();
       document.getElementById('error_msg').innerHTML = "Authentication has failed, please verify credentials you entered.";
     }
    },
    error: function (xhr, ajaxOptions, thrownError) {
        //alert(xhr.status);
        //alert(thrownError);
      }
  });
}


</script>

app/views/oauth/oauth2_authorize.html.erb
<h1>Authorize access to your account</h1>
<p>Would you like to authorize <%= link_to @client_application.name,@client_application.url %> (<%= link_to @client_application.url,@client_application.url %>) to access your account?</p>
<%= form_tag authorize_url do %>
  <%= hidden_field_tag "response_type", params[:response_type]%>
  <%= hidden_field_tag "client_id", params[:client_id]%>
  <%= hidden_field_tag "redirect_uri", params[:redirect_uri]%>
  <%= hidden_field_tag "state", params[:state]%>
  <%= hidden_field_tag "scope", params[:scope]%>

<p>
  <%= check_box_tag 'authorize' %> authorize access
</p>
<p>
  <%= submit_tag %>
</p>
<% end %>