config/routes.rb
Provider::Application.routes.draw do

   name_regex = /[A-Za-z0-9\.\-_]+?/

  scope "#{BASE_URL}" do

    match '/oauth_clients/list_pocs', to: 'oauth_clients#list_pocs', as: :list_pocs
    resources :oauth_clients
    
    match '/oauth/test_request',          :to => 'oauth#test_request',          :as => :test_request
    match '/oauth/token',                 :to => 'oauth#token',                 :as => :token
    match '/oauth/access_token',          :to => 'oauth#access_token',          :as => :access_token
    match '/oauth/request_token',         :to => 'oauth#request_token',         :as => :request_token
    match '/oauth/authorize',             :to => 'oauth#authorize',             :as => :authorize
    match '/oauth/authorize_cli',         :to => 'oauth#authorize_cli',         :as => :authorize_cli
    match '/oauth/authorize_switch_user', :to => 'oauth#authorize_switch_user', :as => :authorize_switch_user
    match '/oauth',                       :to => 'oauth#index',                 :as => :oauth
    match '/oauth/authenticate',          :to => 'oauth#authorize',             :as => :authorize
  
    #Jenkins routes
    match '/login/oauth/authorize',     :to => 'oauth#authorize',     :as => :authorize
    match '/login/oauth/access_token',  :to => 'oauth#access_token',  :as => :access_token
    match '/login/oauth/request_token', :to => 'oauth#request_token', :as => :request_token
    match '/login/oauth/token',         :to => 'oauth#token',         :as => :token    
    
    match '/oauth/login',        :to => 'oauth#login',        :as => :login
    match '/oauth/login_as',     :to => 'oauth#login_as',     :as => :login_as
    match '/oauth/be_admin',     :to => 'oauth#be_admin',     :as => :be_admin
    match '/oauth/be_developer', :to => 'oauth#be_developer', :as => :be_developer
    
  	#API Documentation
  	match '/rest_api', :to => 'rest_api#index'
  	
    match '/authenticate',          :to => 'application#authenticate'
    match '/authenticate_user',     :to => 'application#authenticate_user'
    match '/authentication_failed', :to => 'application#authentication_failed'
    
    root :to => "application#index"
 
    namespace :api do
      match "getInfo"                      => "user#info" #keep old naming used in first version
      match "user.info"                    => "user#info"
      match "user.all_info"                => "user#all_info"
      match "user.name"                    => "user#name"
      match "user.login"                   => "user#login"
      match "user.email"                   => "user#email"
      match "user.groups"                  => "user#groups"
      match "user.all_groups"              => "user#all_groups"
      match "user.firstname"               => "user#firstname"
      match "user.lastname"                => "user#lastname"
      match "user.belongs_to_group"        => "user#belongs_to_group"
      match "user.all_info"                => "user#all_info"      
      match "users/:name"                  => "users#user_info", :name => name_regex, :format => /json|xml|yaml/
      match "users/:name/belongs_to_group" => "users#user_belongs_to_group" , :name =>name_regex, :format => /json|xml|yaml/
      match "users/:name/get_devserver"    => "users#user_devserver", :name => name_regex, :format => /json|xml|yaml/
      match "users/:name/all_info"         => "users#user_all_info", :name => name_regex, :format => /json|xml|yaml/
      match "users/:name/groups"           => "users#user_groups", :name => name_regex, :format => /json|xml|yaml/
      match "users/:name/all_groups"       => "users#user_all_groups", :name => name_regex, :format => /json|xml|yaml/
    end
 
    match "/check" => "application#check"
    match "/401"   => "errors#unauthorized"
    match "/404"   => "errors#not_found"
    match '*path'  => "errors#not_found"
     
  end
  
end

app/controllers/oauth_clients_controller.rb
require "statsd_manager"

class OauthClientsController < ApplicationController

  before_filter :login_required
  before_filter :get_client_application, :only => [:show, :edit, :update, :destroy]
 
  add_breadcrumb "Application List", {controller: "oauth_clients"}

  alias :login_required :authenticate_user!

  # Index page to list registered applications
  #
  # * *Call*    :
  #   - GET /BASE_URL/oauth_clients
  # * *Formats*    :
  #   - html
  #    
  def index
    @all_client_applications = ClientApplication.all.sort {|a,b| a.name <=> b.name }
    @client_applications = current_user.role.client_applications
    @tokens = current_user.tokens.find :all, :conditions => 'oauth_tokens.invalidated_at is null and oauth_tokens.authorized_at is not null'
  end

  # Form to declare a new application
  #
  # * *Call*    :
  #   - GET /BASE_URL/oauth_clients/new
  # * *Formats*    :
  #   - html
  #      
  def new
    @client_application = ClientApplication.new
  end


  # Method to register a new client application
  #
  # * *Call*    :
  #   - POST /BASE_URL/oauth_clients/1
  # * *Formats*    :
  #   - html
  # * *Args*    :
  #   - :client_application => {:name => "Client Application Name", :url => "Application URL", :support_url => "Application Support URL", :callback_url => "Application Callback URL", :poc => "Point Of Contact" }
  #
  def create
    @client_application = current_user.role.client_applications.build(params[:client_application])
    if @client_application.save
      flash[:notice] = "Registered '#{@client_application.name}' successfully"
      statsd = StatsManager.new
      statsd.feedClientApplicationMetric
      redirect_to :action => "show", :id => @client_application.id
    else
      flash.now[:error] = "Registration failed. #{@client_application.errors.full_messages}"
      render :action => "new"
    end
  end

  # Show client application information
  #
  # * *Call*    :
  #   - GET /BASE_URL/oauth_clients/show/1
  # * *Formats*    :
  #   - html
  # * *Args*    :
  #   - None
  #  
  def show
  end

  # Edit client application information
  #
  # * *Call*    :
  #   - GET /BASE_URL/oauth_clients/edit/1
  # * *Formats*    :
  #   - html
  # * *Args*    :
  #   - None
  #    
  def edit
  end

  # Method to update an existing client application 
  #
  # * *Call*    :
  #   - PUT /BASE_URL/oauth_clients/1
  # * *Formats*    :
  #   - html
  # * *Args*    :
  #   - :client_application => {:name => "Client Application Name", :url => "Application URL", :support_url => "Application Support URL", :callback_url => "Application Callback URL", :poc => "Point Of Contact" }
  #  
  def update
    if @client_application.update_attributes(params[:client_application])
      flash[:notice] = "Updated the client information of '#{@client_application.name}' successfully"      
      redirect_to :action => "show", :id => @client_application.id
    else
      flash.now[:error] = "Update failed for client application '#{@client_application.name}'. #{@client_application.errors.full_messages}"
      render :action => "edit"
    end
  end

  # Method to delete an existing client application 
  #
  # * *Call*    :
  #   - DELETE /BASE_URL/oauth_clients/1
  # * *Formats*    :
  #   - html
  # * *Args*    :
  #   - None
  #    
  def destroy
    @client_application.destroy
    statsd = StatsManager.new
    statsd.feedClientApplicationMetric
    flash[:notice] = "Destroyed the client application registration"
    redirect_to :action => "index"
  end

  # Page to list points of contact
  #
  # * *Call*    :
  #   - GET /BASE_URL/oauth_clients/list_pocs
  # * *Formats*    :
  #   - html
  #    
  def list_pocs
    if current_user.has_a_role_of("developer")      
      redirect_to oauth_clients_path, flash: { warning: "You are not allowed to see list of POCs when having a 'developer' role." }
    else
      #get app list per POC 
      @all_pocs = Hash.new([])
      ClientApplication.all.each do |client|
        if @all_pocs[client.poc].empty?
          @all_pocs[client.poc] = [ client.name ]
        else
          @all_pocs[client.poc].push(client.name)
        end
      end
      #get POC list filtering out default 'Not defined' POC
      @all_poc_names = @all_pocs.keys.keep_if { |poc| ! ( poc =~ /^Not defined$/ ) }.sort.join(", ")
      #rework POC app list sorting and joining app names
      @all_pocs.each do |poc, apps|
        @all_pocs[poc] = apps.sort.join(" / ")
      end      
    end
  end
  
  private
  # Helper method to retrieve client application looking at the logged user role
  
  def get_client_application
    unless @client_application = current_user.role.client_applications.find(params[:id])
      flash.now[:error] = "Wrong application id"
      raise ActiveRecord::RecordNotFound
    end
  end
end

app/views/oauth_clients/_form.html.erb
<div class="field">
  <label for="client_application_name"><%=ClientApplication.attribute_text_label(:name)%>*</label><br/>
  <%= f.text_field :name %>
</div>
<div class="field">
  <label for="client_application_url"><%=ClientApplication.attribute_text_label(:url)%>*</label><br/>
  <%= f.text_field :url %>
</div>
<div class="field">
  <label for="client_application_callback_url"><%=ClientApplication.attribute_text_label(:callback_url)%>*</label><br/>
  <%= f.text_field :callback_url %>
</div>
<div class="field">
  <label for="client_application_support_url"><%=ClientApplication.attribute_text_label(:support_url)%></label><br/>
  <%= f.text_field :support_url %>
</div>
<div class="field">
  <label for="client_application_poc"><%=ClientApplication.attribute_text_label(:poc)%>* <font size="-2">(Responsible of the application)</font></label><br/>
  <%= f.text_field :poc %>
</div>

app/views/oauth_clients/edit.html.erb
<h1>Edit an application</h1>
<%= form_for @client_application, :url => oauth_client_path(@client_application), :html => {:method => :put} do |f| %>
       <%= render :partial => "form", :locals => { :f => f } %>
       <%= submit_tag "Edit" %>
<% end %>
<%= link_to 'Show', oauth_client_path(@client_application) %> |
<%= link_to 'Back', oauth_clients_path %>

app/views/oauth_clients/index.html.erb
	<h1>List of registered applications</h1>
	<% if current_user.has_a_role_of("admin") -%>
		<h3><%= link_to "Register a new application", :action => :new %></h3>	
		<% if @client_applications.empty? %>
		  <p>
		    You must register a web application before it can make OAuth requests to this service
		  </p>
		<% end %>
	<% end %>	
	
	<br />
	<table class="table table-striped">
	  <tr>
	  	<th>Application</th>
	  	<th>Registered on</th>
	  	<% if current_user.has_a_role_of("admin") -%>
	  	  	<th><%=ClientApplication.attribute_text_label(:poc)%></th>
		  	<th>Actions</th>
		 <% end %>
	  </tr>
	  <% @all_client_applications.each do |client|%>
	    <tr>
	      <td><%= link_to client.name, client.url %></td>
	      <td><%= client.created_at %></td>
	      <% if current_user.has_a_role_of("admin") -%>
	        <td><%=client.poc%></td>
		  	<td>
			  <div>
			    <%= link_to 'Show', oauth_client_path(client) %> -
			    <%= link_to 'Edit', edit_oauth_client_path(client) %> -
			    <%= link_to 'Delete', oauth_client_path(client), :confirm => "Are you sure?", :method => :delete %>
			  </div>  	
		  	</td>
		 <% end %>
	    </tr>
	  <% end %>
	
	</table>

app/views/oauth_clients/list_pocs.html.erb
<h1>List of POCs</h1>
<br>
<%=@all_poc_names%>
<br><br>
<h2>Details</h2>
<dl>
  <% @all_pocs.sort.each do |poc, apps| %>
  <dt><%=poc%></dt>
  <dd><font size="-2"><%=apps%></font><dd>
  <% end %>
</dl>

app/views/oauth_clients/new.html.erb
<h1>Register a new application</h1>
<%= form_for :client_application, :url => { :action => :create } do |f| %>
   <%= render :partial => "form", :locals => { :f => f } %>
   <%= submit_tag "Register" %>
<% end %>

app/views/oauth_clients/show.html.erb
<h1>Application : <%=@client_application.name %></h1>
<br>
<h2>Application Details</h2>
<table>
<% [ :name, :url, :callback_url, :support_url, :poc ].each do |attr| %>
  <tr>
  <td><strong><%=ClientApplication.attribute_text_label(attr)%> : </strong></td>
  <td><code><%=@client_application.send(attr)%></code></td>
  </tr>
<% end %>
</table>
<br>
<h2>OAuth Details</h2>
<p>Information to communicate by mail to responsible of the application (<%=@client_application.poc%>, see POC above).</p>
<table> 
<% [ :key, :secret ].each do |attr| %>
  <tr>
  <td><strong><%=ClientApplication.attribute_text_label(attr)%> : </strong></td>
  <td><code><%=@client_application.send(attr) %></code></td>
  </tr>
<% end %>
<tr>
<td><strong>Request Token URL : </strong></td>
<td><code>http<%='s' if request.ssl? %>://<%= request.host_with_port %><%=@client_application.oauth_server.request_token_path.gsub("/oauth/","/#{BASE_URL}/oauth/").gsub("request_","") %></code></td>
</tr>
<tr>
<td><strong>Access Token URL : </strong></td>
<td><code>http<%='s' if request.ssl? %>://<%= request.host_with_port %><%=@client_application.oauth_server.access_token_path.gsub("/oauth/","/#{BASE_URL}/oauth/") %></code></td>
</tr>
<tr>
<td><strong>Authorize URL : </strong></td>
<td><code>http<%='s' if request.ssl? %>://<%= request.host_with_port %><%=@client_application.oauth_server.authorize_path.gsub("/oauth/","/#{BASE_URL}/oauth/") %></code></td>
</tr>
</table>
<br><p>NOTE : We support hmac-sha1 (recommended) as well as plain text in ssl mode.</p>
<%= link_to 'Edit', edit_oauth_client_path(@client_application) %> |
<%= link_to 'Back', oauth_clients_path %>